<?php
$playlists = rows('SELECT idplaylist, nombre, imagen FROM playlist WHERE idusuario = ? ORDER BY idplaylist DESC', 'i', [$user['idusuario']]);
$libraryIds = array_column(rows('SELECT idcancion FROM biblioteca_tiene_cancion WHERE idbiblioteca = ?', 'i', [$user['idbiblioteca']]), 'idcancion');
$allSongs = catalogue();
$artists = rows('SELECT idartista, nombre, imagen FROM artista ORDER BY idartista');
function song_button(array $song, string $extra = ''): string {
    return '<button type="button" class="songItem ' . e($extra) . '" data-song="' . (int)$song['id'] . '"><img src="' . e($song['poster']) . '" alt=""><span><strong>' . e($song['name']) . '</strong><small>' . e($song['artist']) . '</small></span><span class="play-mark" aria-hidden="true">▶</span></button>';
}
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="<?= e(csrf()) ?>"><title><?= e($pageTitle) ?> · Versix</title><link rel="stylesheet" href="style.css"><link rel="stylesheet" href="portfolio.css"><script src="player-core.js" defer></script><script src="app.js" defer></script></head>
<body class="music-body"><header class="music-app">
<aside class="menu_side"><a class="brand" href="inicio.php">Versix</a><nav class="side-nav"><a href="inicio.php">⌂ Inicio</a><a href="playlist_formulario.php">＋ Crear playlist</a></nav><h2 class="side-title">Tu biblioteca</h2><div class="menu_song" id="library-list">
<?php foreach ($playlists as $list): ?><a class="playlist-link" href="playlist_pagina.php?id=<?= (int)$list['idplaylist'] ?>"><img src="<?= $list['imagen'] === '' ? 'img/playlist.svg' : 'cover.php?id=' . (int)$list['idplaylist'] ?>" alt=""><span><?= e($list['nombre']) ?><small>Playlist</small></span></a><?php endforeach; ?>
<?php foreach ($allSongs as $song): if (in_array($song['id'], $libraryIds)) echo song_button($song, 'library-song'); endforeach; ?>
<p id="empty-library" class="muted" <?= $libraryIds || $playlists ? 'hidden' : '' ?>>Guarda una canción o crea tu primera playlist.</p></div>
<form method="post" action="logout.php" class="logout"><?= csrf_input() ?><button type="submit">Cerrar sesión</button></form></aside>
<main class="song_side"><nav class="top-nav"><label class="search-label" for="search">Buscar música</label><input type="search" id="search" placeholder="Canciones o artistas…" autocomplete="off"><span class="user-name"><?= e($user['usuario']) ?></span></nav><div id="search-results" class="search-results" hidden></div>
<section class="hero"><p class="eyebrow">DALE AL PLAY</p><h1><?= e($pageTitle) ?></h1><p><?= e($pageSubtitle) ?></p><?php if ($visibleSongs): ?><button class="primary" type="button" data-song="<?= (int)$visibleSongs[0]['id'] ?>">▶ Escuchar</button><?php endif; ?><div class="hero-orbit" aria-hidden="true"></div></section>
<section class="catalog-section"><h2>Tu selección musical</h2><div class="song-grid">
<?php foreach ($visibleSongs as $song) echo song_button($song, 'catalog-card'); ?>
<?php if (!$visibleSongs): ?><p class="muted">Esta playlist está vacía. Reproduce una canción desde Inicio y guárdala aquí.</p><?php endif; ?></div></section>
<section class="catalog-section"><h2>Explora artistas</h2><div class="artist-grid"><?php foreach ($artists as $artist): ?><a href="artista.php?id=<?= (int)$artist['idartista'] ?>"><img src="<?= e($artist['imagen']) ?>" alt=""><strong><?= e($artist['nombre']) ?></strong></a><?php endforeach; ?></div></section><p class="catalog-note">Colección de demostración · Sonidos sintéticos originales</p></main>
<footer class="master_play"><div class="now-playing"><img id="poster_master_play" src="img/playlist.svg" alt=""><div><strong id="title">Elige una canción</strong><small id="artist-title">Tu música te espera</small></div></div>
<div class="playback"><div class="controls"><button id="mode" type="button" title="Modo de reproducción" aria-label="Modo de reproducción: secuencial">→</button><button id="back" type="button" aria-label="Canción anterior">⏮</button><button id="masterPlay" class="play-main" type="button" aria-label="Reproducir">▶</button><button id="next" type="button" aria-label="Canción siguiente">⏭</button><a id="download_music" href="#" download aria-label="Descargar audio" hidden>↓</a></div><div class="seek-row"><span id="currentStart">0:00</span><input type="range" id="seek" min="0" max="100" value="0" step="0.1" aria-label="Posición de reproducción"><span id="currentEnd">0:00</span></div></div>
<div class="save-controls"><button id="guardarBiblio" type="button">＋ Biblioteca</button><label for="opcionesDesplegables" class="sr-only">Playlist de destino</label><select id="opcionesDesplegables"><option value="">Elige playlist</option><?php foreach ($playlists as $list): ?><option value="<?= (int)$list['idplaylist'] ?>"><?= e($list['nombre']) ?></option><?php endforeach; ?></select><button id="guardarPlaylist" type="button">＋ Playlist</button><label for="vol" class="sr-only">Volumen</label><input id="vol" type="range" min="0" max="100" value="60" aria-label="Volumen"></div></footer></header><div id="status" class="status" role="status" aria-live="polite" hidden></div></body></html>
